name: QR App CI

#Runs CI when you:
#push to main
#open/update a pull request

#you can do something like this if you have multiple branches
#branches:
#  - main
#  - develop

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


#INDENTION MATTERS in YAML! Be careful with spaces/tabs
# “job” = one pipeline run
#Uses a Linux VM to execute your steps
#starting on "Checkout code": This pulls your repo into the runner
#starting on "Setup Node": Ensures consistent Node version (very important in CI)
#starting on "Install dependencies": npm install Same as running locally
#starting on "Build project": This is your main CI check. If build fails → pipeline fails 
#starting on "Run tests": Run tests (if you have any)
jobs:
  customBuildStep1:
    runs-on: ubuntu-latest
    #OR you can use a container with Node 20 to ensure consistent environment
    #container:
    #  image: node:20
    steps:
      #these lines taht start with "- name" are just for readability in the GitHub Actions UI, they don't affect functionality
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # Optional
      - name: Run tests
        run: npm test -- --watchAll=false
      